language: ruby
sudo: false
cache: bundler

rvm:
  - 2.3.7

env:
  - DB=redis

before_install:
  - gem update --system
  - gem --version
  - gem install bundler

install:
  - bundle install

after_success:
  - echo "YaY!"
